Models/Post.cs
using System;
using System.Collections.Generic;

namespace OpenMindsForum.Models;

public partial class Post
{
    public int PostId { get; set; }

    public string Title { get; set; } = null!;

    public string PostContent { get; set; } = null!;

    public int SubjectId { get; set; }

    public DateTime PostStamp { get; set; }

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual Subject Subject { get; set; } = null!;
}

Controllers/CommentsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OpenMindsForum.Models;
using OpenMindsForum.ViewModels;

namespace OpenMindsForum.Controllers
{
    public class CommentsController : Controller
    {
        private readonly OpenMindsForumContext _context;

        public CommentsController(OpenMindsForumContext context)
        {
            _context = context;
        }

        // GET: CommentsController/Create
        public ActionResult Create()
        {
            return View();
        }

        [Route("Details")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateCommentViewModel createComment, int id)
        {
            if (ModelState.IsValid)
            {
                var newComment = new Comment
                {
                    PostId = id,
                    Title = createComment.title,
                    CommentContent = createComment.content,
                    CommentStamp = DateTime.Now,
                };
                _context.Add(newComment);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Posts", new { id = id });
            }
            return NotFound();
        }
    }
}

Controllers/PostsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OpenMindsForum.Models;
using OpenMindsForum.ViewModels;

namespace OpenMindsForum.Controllers
{
    public class PostsController : Controller
    {
        private readonly OpenMindsForumContext _context;

        public PostsController(OpenMindsForumContext context)
        {
            _context = context;
        }

        // GET: Posts/5
        public IActionResult Index(int? id)
        {

            var model = new List<ListPostViewModel>();
            var postlist = _context.Posts.Where(s => s.SubjectId == id).Include(p => p.Subject).Include(y => y.Comments);
            
            if (id==0 || id==null)
            {
                postlist = _context.Posts.Include(p => p.Subject).Include(y => y.Comments);
            }

            foreach (var item in postlist)
            {
                model.Add(new ListPostViewModel
                {
                    postID = item.PostId,
                    title = item.Title,
                    content = item.PostContent,
                    subject = item.Subject.Name,
                    stamp = item.PostStamp,
                    comments = item.Comments.Count()

                });
            }

            return View(model);
        }

        [Route("Details")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .Include(p => p.Subject).Include(y => y.Comments)
                .FirstOrDefaultAsync(m => m.PostId == id);

            if (post == null)
            {
                return NotFound();
            }
            var model = new DetailPostCommentsViewModel
            {
                postID= post.PostId,
                title = post.Title,
                content = post.PostContent,
                stamp = post.PostStamp,
                subject = post.Subject.Name,
                comments = post.Comments.ToList(),

            };

            return View(model);
        }

        // GET: Posts/Create
        public IActionResult Create()
        {
            var model = new CreatePostViewModel();
            SelectListItem firstBlank = new SelectListItem();
            model.subjectList.Insert(0, firstBlank);
            var subjects = _context.Subjects;

            foreach (var item in subjects)
            {
                model.subjectList.Add(new SelectListItem
                {
                    Value = Convert.ToString(item.SubjectId),
                    Text = item.Name
                });
            }
            return View(model);
        }

        // POST: Posts/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreatePostViewModel postViewModel)
        {
            if (ModelState.IsValid)
            {
                var postModel = new Post
                {
                    Title = postViewModel.title,
                    PostContent = postViewModel.content,
                    PostStamp = DateTime.Now,
                    SubjectId = postViewModel.subjectID,
                };
                _context.Add(postModel);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Posts", new { id = postModel.PostId });
            }
            return View(postViewModel);
        }
    }
}

Views/Posts/Create.cshtml
@model OpenMindsForum.ViewModels.CreatePostViewModel

@{
    ViewData["Title"] = "Create";
}
<br />
<h3>Create a post</h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="title" class="control-label"></label>
                <input asp-for="title" class="form-control" />
                <span asp-validation-for="title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="subjectID" class="control-label"></label>
                <select asp-for="subjectID" class="form-select" asp-items="Model.subjectList"></select>
                <span asp-validation-for="subjectID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="content" class="control-label"></label>
                <textarea input asp-for="content" 
                class="form-control" id="exampleTextarea" rows="10" style="height: 400px; width: 800px;"></textarea>
                <span asp-validation-for="content" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Publish" class="btn btn-outline-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Posts/Details.cshtml
@model OpenMindsForum.ViewModels.DetailPostCommentsViewModel

@{
    ViewData["Title"] = "Details";
}
<br />
<h4>@Html.DisplayFor(model => model.title)</h4>

<div>
    <p class="text-body-tertiary">Posted: <span class="badge rounded-pill bg-dark">@Html.DisplayFor(model => model.stamp)</span></p>
    
</div>

<div>
    <hr />
    <p>@Html.DisplayFor(model => model.content)</p>
    <hr />
</div>
<br />
<div class="list-group">
    <h5>Comments</h5>
    @foreach (var item in Model.comments)
    {
        <a class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">@item.Title</h5>
                <small>@item.CommentStamp</small>
            </div>
            <p class="mb-1">@item.CommentContent</p>
        </a>

    }
</div>
<hr />
<form asp-controller="Comments" asp-action="Create" method="post" asp-route-id="@Model.postID">
    <div class="card border-secondary mb-3" style="max-width: 50rem;">
        <div class="card-header">
            <h5 class="card-title">Create a comment</h5>
        </div>
        <div class="form-group">
            <label asp-for="@Model.createComment.title" class="control-label"></label>
            <input asp-for="@Model.createComment.title" class="form-control" />
            <span asp-validation-for="@Model.createComment.title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.createComment.content" class="control-label"></label>
            <textarea input asp-for="@Model.createComment.content" class="form-control" rows="7"></textarea>
            <span asp-validation-for="@Model.createComment.content" class="text-danger"></span>
        </div>
        <div class="form-group" align="right" margin="100">
            <input type="submit" value="Publish" class="btn btn-outline-primary" />
        </div>
    </div>
</form>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Posts/Index.cshtml
@model IEnumerable<OpenMindsForum.ViewModels.ListPostViewModel>

@{
    ViewData["Title"] = "Index";
}
<br />
<h3>All posts</h3>
<hr />
<div class="text-center">
<table class="table">
        <thead>
            <tr>
                <th style="text-align: left">
                    @Html.DisplayNameFor(model => model.title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.stamp)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.subject)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.comments)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model) 

            {
                <tr>
                    <td style="text-align: left">
                            <a asp-controller="Posts" asp-action="Details" asp-route-id="@item.postID">@Html.DisplayFor(modelItem => item.title)</a>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.stamp)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.subject) @*lägg till länk som tar till alla posts för kategorin*@
                    </td>
                        <td>
                            <span class="badge bg-primary rounded-pill">@Html.DisplayFor(modelItem => item.comments)</span>
                        </td>
                </tr>
            }
        </tbody>
</table>
</div>
<hr />
<br />
<a asp-action="Create"><button type="button" class="btn btn-outline-primary">Create New</button></a>
    

    
 